name: Test
on:
  push:
    branches: [ "main" ]

jobs:
  analysis-job:
    runs-on: ubuntu-latest
    container:
      image: 0xhexdec/code-analysis-test:2.1
      env:
        ANALYSIS_REMOTE_URL: https://github.com/${{github.repository}}.git
        ANALYSIS_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Run analysis
        working-directory: /home/jboss
        run: java -jar quarkus-run.jar
        
