name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: 0xhexdec/code-analysis-test:2.1
      env:
        ANALYSIS_REMOTE_URL: https://gitlab.com/0xhexdec/busydoingnothing.git
        ANALYSIS_BRANCH: master
    steps:
      - name: Check for dockerenv file
        working-directory: /home/jboss
        run: java -jar quarkus-run.jar
        
