name: Test
on:
  push:
    branches: [ "main" ]

jobs:
  analysis-job:
    runs-on: ubuntu-latest
    container:
      image: 0xhexdec/code-analysis-test:2.1
      env:
        GRPC_HOST: ${{vars.GRPC_HOST}}
        GRPC:PORT: ${{vars.GRPC_PORT}}
        ANALYSIS_REMOTE_URL: https://github.com/${{github.repository}}.git
        ANALYSIS_BRANCH: ${{ github.ref_name }}
        ANALYSIS_FETCH_REMOTE: "true"
        ANALYSIS_SEND_TO_REMOTE: "true"
        ANALYSIS_CALCULATE_METRICS: "true"
        ANALYSIS_RESOLVE_WILDCARDS: "true"
        
    steps:
      - name: Run analysis
        working-directory: /home/jboss
        run: java -jar quarkus-run.jar
        
