name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: 0xhexdec/code-analysis-test:2.1
      env:
        NODE_ENV: development
